# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   - {id: 4, size: 0.044}
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
tag_bundles:
  [
    {
      name: 'CUSTOM_BUNDLE_NAME',
      layout:
        [

          {id: 10, size: 0.04, x: -0.085, y: 0.07, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 11, size: 0.04, x: 0.085, y: 0.07, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 12, size: 0.04, x: -0.085, y: -0.07, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 13, size: 0.04, x: 0.085, y: -0.07, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},       
          
          # {id: 10, size: 0.04, x: 0, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          # {id: 11, size: 0.04, x: 0.17, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          # {id: 12, size: 0.04, x: 0, y: -0.14, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          # {id: 13, size: 0.04, x: 0.17, y: -0.14, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},         
        ]
    },
  ]
# tag_bundles:
#   [
#   ]
